import {addIcons} from 'ionicons';
import {
  addOutline,
  homeOutline,
  statsChartOutline,
  timeOutline,
  checkmarkDoneOutline,
  calendarOutline,
  flashOutline,
  cloudOfflineOutline,
  informationCircleOutline,
  checkmarkCircleOutline,
  settingsOutline,
  trashOutline,
  alertCircleOutline,
  shareOutline,
  codeDownloadOutline,
  logoAndroid,
  ellipsisVertical,
  cloudDownloadOutline,
  warningOutline,
  desktopOutline,
  downloadOutline,
  documentTextOutline,
  createOutline,
  trashBinOutline
} from 'ionicons/icons';

export function registerIcons() {
  addIcons({
    addOutline,
    homeOutline,
    statsChartOutline,
    timeOutline,
    checkmarkDoneOutline,
    calendarOutline,
    flashOutline,
    cloudOfflineOutline,
    informationCircleOutline,
    checkmarkCircleOutline,
    settingsOutline,
    trashOutline,
    alertCircleOutline,
    shareOutline,
    codeDownloadOutline,
    logoAndroid,
    ellipsisVertical,
    cloudDownloadOutline,
    warningOutline,
    desktopOutline,
    downloadOutline,
    documentTextOutline,
    createOutline,
    trashBinOutline
  });
}
